# Required. client display name
clientName: 

# Optional. hostname of the client should match the service fqdn.
clientHostName: 

image: 
  # Optional. Default value is commserve
  repository: 
  # Optional. Overrides gobal value. Must end with /
  registry: 
  # Optional. Overrides gobal value. Default is latest
  tag: 

# Optional. Applies to the network gateway service (cvfwd) of the commserve. Default service type is LoadBalancer. The service is created ending with the word gateway
serviceType: 

# Optional. Will be merged with global annotations and also override matching global annotations
deploymentannotations:

# Optional. Applies to the network gateway service of the commserve. Will be merged with global annotations and also override matching global annotations
serviceannotations:

# Optional. Applies to the internal services of the commserve.
csserviceannotations:

# Optional. Applies to the commcell console services of the commserve.
consoleserviceannotations:

# Optional. Deployment requests and limits. Enable only those values that need to be set. This also overrides any global values
# resources:
#   requests:
#     memory: 
#     cpu:
#   limits:
#     memory:
#     cpu: 

# storage class just for cs image
storageClass:
  # Optional. Name of the storage class for cs database. Default storage class will be used if not specified
  csdb: 
  # Optional. default is "100Gi" 
  csdb_size: 
